### ISSUE TITLE
login de usuario

### ISSUE THREAD

**Issue by JorgeFriasD** [dtsyosh/Bugueria#6]
- Definir hierarquia de usuário:
Usuário: segue a visão normal, podendo ter visibilidade as paginas relacionadas a criação de pedido
Caixa: Cancelar, apresentar/listar o pedido em andamento (Via, arquivo), fechar o pedido.
Administrador: Acesso a todas as funcionalidades do sistema.

**Comment by dtsyosh** [comment]
Login e bloqueio de views já implementados.... Falta criar um menu para o adm administrar os recursos (ingredientes, pizzas, cardapio...), depois que tiver isso feito eu mesclo a branch 'login' com a master
